---
# tasks file for install_cuda

- name: Add cuda-repo
  apt:
    deb: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-repo-ubuntu1804_10.0.130-1_amd64.deb

- name: Add nvidia keys
  apt_key:
    url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
    ## it's apt-key adv --fetch-keys in the manual, yet it works this way

- name: Add nvidia-machine-learning-repo
  apt:
    update_cache: yes
    deb: http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb

- name: Install nvidia-driver
  apt:
    update_cache: yes
    install_recommends: no
    name: nvidia-driver-418
  register: nvidia_driver_installed

- name: Reboot
  reboot:
    reboot_timeout: 600
  when: nvidia_driver_installed.changed
  
- name: Check that GPUs are visible using the nvidia-smi command
  command: nvidia-smi
  register: nvidia_smi_output

- debug:
    msg: "{{nvidia_smi_output.stdout_lines}}"
  failed_when: "ensure_gpu_model_available not in nvidia_smi_output.stdout"

- name: Install cuda
  apt:
    update_cache: yes
    install_recommends: no
    name:
      - cuda-10-0
      - libcudnn7=7.6.0.64-1+cuda10.0
      - libcudnn7-dev=7.6.0.64-1+cuda10.0
  
- name: Install TensorRT
  apt:
    update_cache: yes
    install_recommends: no
    name:
      - libnvinfer5=5.1.5-1+cuda10.0
      - libnvinfer-dev=5.1.5-1+cuda10.0
